Month9/step2
gudrum1983/react-stellar-burger pull request #7
Opened 2023-11-26 19:57 UTC by gudrum1983

Добрый вечер ревьювер! Я очень извиняюсь, но проект не успела доделать до ума, сдаю как есть, что бы на каникулах доделать. 
![котёнок жалостливый](https://github.com/gudrum1983/react-stellar-burger/assets/126697350/10be04cf-3e2c-4b6a-9bae-8e3342ff847a)

2023-11-26 20:49 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Реализовали универсальный веб-сокет
- Сокеты открываются и закрываются согласно брифу
- Есть механизм обновления токена при работе с сокетами
- Данные полученные по сокетам находятся в разных местах стора

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Проект собирается с ошибками eslint. По правилам - нельзя вызывать хуки по условиям, потому что это может нарушить их работу

<img width="959" alt="image" src="https://github.com/gudrum1983/react-stellar-burger/assets/60173362/935769fd-19c9-47ec-9a9d-6c7595b62f0e">

- При переходе по прямой ссылке на заказ - сообщение, что такого заказа нет, хотя он есть

<img width="967" alt="image" src="https://github.com/gudrum1983/react-stellar-burger/assets/60173362/362702f3-bd04-4e90-9d2a-6f3519c99aa0">

**Можно лучше**
- Список Заказов из Истории заказов лучше перевернуть, чтобы последний заказ оказался первым в списке.
- папку build лучше не пушить в github 

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-11-26 20:49 UTC, andryxxa93 commented on src/components/app/app.jsx
> +          <Route path="login" element={<OnlyUnAuth component={<Login/>}/>}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-11-26 20:49 UTC, andryxxa93 commented on src/services/middleware/socket-middleware.js
> +        socket.close = () => {
**Можно лучше**
Так как браузерный веб-сокет не обладает возможностью переподключения из-за обрыва соединения - желательно это делать самому через setTiimeout

2023-11-26 20:49 UTC, andryxxa93 commented on src/services/user/user-action.js
> +          localStorage.removeItem("accessToken");
**Можно лучше**
Строки `accessToken ` и `refreshToken ` повторяются в коде часто, поэтому их следует вынести в константы

2023-12-01 16:06 UTC, gudrum1983 commented on src/services/middleware/socket-middleware.js
> +        socket.close = () => {
Сделано

2023-12-01 16:06 UTC, gudrum1983 commented on src/services/user/user-action.js
> +          localStorage.removeItem("accessToken");
аа...забыла, потом исправлю

2023-12-01 16:07 UTC, gudrum1983 commented on src/components/app/app.jsx
> +          <Route path="login" element={<OnlyUnAuth component={<Login/>}/>}/>
переделала, возможно не везде :(

2023-12-01 19:44 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-12-10 15:44 UTC, merged